name: anthrocult
title: null
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  theme: jekyll-theme-cayman

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

lang: "en"
langs: ["en", "es"]

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  
